### ISSUE TITLE
[Bug] Properties that are flagged un-animatable CAN STILL be tagged A or RA

### ISSUE THREAD

**Issue by BluWizard10** [Thryrallo/ThryEditor#103]
Basically, a lot of the properties that are not supposed to be animated can still be tagged with `A` or `RA`, as of ThryEditor v2.57.0.

According to Poiyomi, they flagged those properties that aren't supposed to be Animated. However, ThryEditor still allows it.

**Comment by Thryrallo** [comment]
@poiyomi note commit message
