### ISSUE TITLE
[Bug] Decal Raycast tool creates excessive calls to Mesh.get_normals

### ISSUE THREAD

**Issue by Myrkie** [Thryrallo/ThryEditor#111]
Attempting to use Decal Raycast in latest versions of Poiyomi causes over 65000 calls to Mesh.Normals resulting in the editor freezing for 30 seconds and the Raycast being unusable. this wasn't always an issue and the same project with a newer version of thry editor and poiyomi has this issue, while a previous one doesn't.

[this seems to have been caused by this commit](https://github.com/Thryrallo/ThryEditor/commit/1152f08fd2be8cef7f7ecb07fb4594587db8d826)
the source of the issue appears to be from [this segment of code](https://github.com/Thryrallo/ThryEditor/blob/master/Editor/DecalSceneTool.cs#L135-L155) after deep profiling the editor

![Unity_iEe7EIROql](https://github.com/user-attachments/assets/20aa6ce9-f9bf-4862-a159-02d9838d79f6)

**Comment by BluWizard10** [comment]
Can confirm. This problem, if left un-patched, freezes Unity much longer the more Material slots a single Mesh has.
