### ISSUE TITLE
Issue including file durring the optimization step. 

### ISSUE THREAD

**Issue by zwparchman** [Thryrallo/ThryEditor#18]
https://github.com/Thryrallo/ThryEditor/blob/364c421007f9c7d4c6b99a6a69cf4646613e5097/Editor/ShaderOptimizer.cs#L1060

I don't understand what the purpose of the above line is. Adding `newTopLevelDirectory` to the absolute file path seems like it is the wrong thing to do conceptually and results in a path like
`#include "Assets\AngryLabs\AudioBump\dev/OptimizedShaders/body/Assets/AngryLabs/AudioBump/AudioBump.cginc"`.

I see a comment explicitly calling this out as desirable, but it feels like an error. Removing the `newTopLevelDirectory` term results in expected desirable behavior.

**Comment by Thryrallo** [comment]
probably fixed
