### ISSUE TITLE
[QoL] Remove the "Lock in Children" lock icon that appears when next to a shader property and only keep it in the right-click menu

### ISSUE THREAD

**Issue by Rivera-IV** [Thryrallo/ThryEditor#56]
Ever since this came to be, I have somehow always ended up mis-clicking and enabling this on random shader properties on accident when just expanding categories in the poi shader.

Sometimes it overlaps with other things in the UI for poi shaders (9.1.2).

To prevent this from occurring, I think that it should only be possible to lock in children if the property is right-clicked and then the option to do so is chosen.

![image_2024-05-01_193238701](https://github.com/Thryrallo/ThryEditor/assets/89464945/fae10e89-550e-4d65-936e-98368c0db67e)
![image_2024-05-01_193531284](https://github.com/Thryrallo/ThryEditor/assets/89464945/9e3cb00a-7b8a-4bad-81a9-5c18457c2389)

**Comment by Thryrallo** [comment]
fixed
