### ISSUE TITLE
[Feature Request] Add an option to turn off sRGB/Linear warnings

### ISSUE THREAD

**Issue by Rivera-IV** [Thryrallo/ThryEditor#62]
Pretty self explanatory, just a toggle or something to turn off these warnings in the UI.
![image](https://github.com/Thryrallo/ThryEditor/assets/89464945/71c6ea7a-0e31-43b4-b95b-1fc20e804935)

**Comment by BluWizard10** [comment]
I would say if we were to add a toggle that controls if those sRGB/Linear Warnings appear or not, a message should be added next to the checkbox telling the user to ensure they understand the difference between sRGB and Linear, and how it can affect appearances in certain areas of the Shader such as Alpha Maps, RGBA Mapping, and MetallicSmoothness mapping.

**Comment by Rivera-IV** [comment]
> I would say if we were to add a toggle that controls if those sRGB/Linear Warnings appear or not, a message should be added next to the checkbox telling the user to ensure they understand the difference between sRGB and Linear, and how it can affect appearances in certain areas of the Shader such as Alpha Maps, RGBA Masking, and MetallicSmoothness mapping.
> 
> I understand that the warnings are there for a reason because of those things, as most Avatar Creators most of the time don't know what they are doing. So keep the Warnings on by default, and only have the override be a per project basis.

I agree with Blu here :)
