### ISSUE TITLE
[VRAM Calculator] Add ability to locate where a texture is used on a material, not just which material

### ISSUE THREAD

**Issue by sacred0** [Thryrallo/ThryEditor#71]
Using the GUID of a texture, it is possible to locate where textures are used in a material by finding the GUID from the texture's .meta file and looking for where it's referenced in a material. 

This would help locate stray textures in materials that shouldn't be there, or to simply find which section it's being used in.

**Comment by Thryrallo** [comment]
![image](https://github.com/user-attachments/assets/f7e8344f-ca09-4de4-b949-f13c2e99d229)
Is this kinda what you mean?

**Comment by sacred0** [comment]
Yes, something like that ^^ This would definitely help a lot in its current state. I suppose an extra bit of polish to this could also format it using the name of the slot from the shader UI, as well as which section it's in. In this case, something like "New Material 3 -> "_Matcap" (Shading > Matcap 0 > Matcap). This will likely increase the complexity, so it's up to you whether or not you want to do something like that. I suppose something like that may also make it more less universal and more Poiyomi dependant.

**Comment by Thryrallo** [comment]
Done
