### ISSUE TITLE
Global Theme Selections Don't Copy & Paste

### ISSUE THREAD

**Issue by ZenithVal** [Thryrallo/ThryEditor#79]
Workflow in shambles.
![image](https://github.com/user-attachments/assets/9e240e20-43f9-40c2-b3ae-d3074ffaf758)

**Comment by Martin-H2** [comment]
BUG: when you copy values between sections / materials, everything gets copied, but not the "Theme Color #" selection
![image](https://github.com/user-attachments/assets/60c2e124-5ee4-4d40-bd53-262b982324ea)
