### ISSUE TITLE
Search UI does not directly reveal matches

### ISSUE THREAD

**Issue by teehzero** [Thryrallo/ThryEditor#83]
Relevant Discord thread: https://discord.com/channels/550477546958094348/602917015883350041/1276609104231661710
![image](https://github.com/user-attachments/assets/1038e269-9e19-40f2-b49b-6f0df03d7ea0)

This user was searching for Parallax Heightmapping. The search UI correctly discarded irrelevant results, but did not directly expose the desired match to the user. Where possible, modules/submodules should drill down to expose the user's matched string, preferably with some kind of highlighting.

**Comment by Thryrallo** [comment]
should be better in newer version
