### ISSUE TITLE
Marking a Preset no longer exist in context menu

### ISSUE THREAD

**Issue by BluWizard10** [Thryrallo/ThryEditor#95]
As of v2.56.5 (included in Poiyomi 9.0.60), this no longer exists (see screenshot)

This caused the instructions for marking a Preset [as documented here](https://www.poiyomi.com/thryeditor/presets#how-to-create-a-preset) completely nulled.

Please fix!

![Thry_MarkAsPreset](https://github.com/user-attachments/assets/5255569c-4958-47ef-adeb-01492921a344)

**Comment by Thryrallo** [comment]
![image](https://github.com/user-attachments/assets/1bd2695c-292e-4463-afd2-84d3b8da191a)
This was intentionally moved to the material UI to declutter the asset context menu.
